In [ ]:
# import library yang akan digunakan
import numpy as np
import pandas as pd

In [ ]:
data= np.array([
    [2.5, 2.4, 3.5, 3.6],
    [0.5, 0.7, 1.2, 1.3],
    [2.2, 2.9, 3.0, 3.4],
    [1.9, 2.2, 2.5, 2.7],
    [3.1, 3.6, 4.1, 4.0],
    [2.3, 2.7, 3.1, 3.0],
    [2.0, 1.6, 2.3, 2.4],
    [1.0, 1.1, 1.5, 1.6],
    [1.5, 1.6, 2.0, 2.1],
    [1.1, 0.9, 1.3, 1.4]
])
data

array([[2.5, 2.4, 3.5, 3.6],
       [0.5, 0.7, 1.2, 1.3],
       [2.2, 2.9, 3. , 3.4],
       [1.9, 2.2, 2.5, 2.7],
       [3.1, 3.6, 4.1, 4. ],
       [2.3, 2.7, 3.1, 3. ],
       [2. , 1.6, 2.3, 2.4],
       [1. , 1.1, 1.5, 1.6],
       [1.5, 1.6, 2. , 2.1],
       [1.1, 0.9, 1.3, 1.4]])

In [ ]:
#stanmdarisasi
mean= np.mean(data, axis=0)
std_dev= np.std(data, axis=0)
Z= (data-mean)/std_dev
Z

array([[ 0.92627881,  0.47833912,  1.13455516,  1.16201358],
       [-1.7585873 , -1.41276904, -1.35066091, -1.3833495 ],
       [ 0.52354889,  1.0345474 ,  0.5942908 ,  0.94067766],
       [ 0.12081898,  0.25585581,  0.05402644,  0.16600194],
       [ 1.73173864,  1.813239  ,  1.78287239,  1.60468542],
       [ 0.6577922 ,  0.81206409,  0.70234367,  0.49800582],
       [ 0.25506228, -0.41159413, -0.16207931, -0.16600194],
       [-1.08737078, -0.96780241, -1.02650229, -1.05134562],
       [-0.41615425, -0.41159413, -0.48623793, -0.49800582],
       [-0.95312747, -1.19028572, -1.24260803, -1.27268154]])

In [ ]:
#HITUNG MATRIKS COVARIAN
cov_matrix = np.cov(Z, rowvar=False)
cov_matrix

#HITUNG NILAI EIGEN DAN VECTOR EIGEN
eigenvalues, eigenvectors = np.linalg.eigh(cov_matrix)

#hitung proporsi variansi dari niali eigen
total_variance = np.sum(eigenvalues)
proportions = eigenvalues / total_variance
#HITUNG KONTRIBUSI VARIANSI DARI NILAI EIGEN
cumulative_variance = np.cumsum(proportions)

#menampilkan hasil
print("Nilai Eigen:")
print(eigenvalues)
print("\nVector Eigen:")
print(eigenvectors)
print("\nProporsi Variansi:")
print(proportions)
print("\nKontribusi Variansi:")
print(cumulative_variance)


Nilai Eigen:
[0.01006116 0.0358081  0.06538576 4.33318943]

Vector Eigen:
[[ 0.18010494  0.59069863 -0.60891055 -0.4978607 ]
 [-0.02652168  0.38947111  0.77557842 -0.49607153]
 [-0.76652797 -0.36220899 -0.16639394 -0.50354004]
 [ 0.61586824 -0.60678829  0.00437079 -0.50248899]]

Proporsi Variansi:
[0.00226376 0.00805682 0.0147118  0.97496762]

Kontribusi Variansi:
[0.00226376 0.01032058 0.02503238 1.        ]


In [ ]:
#menentukan ambang batas atau threshold dala pemilhan eigen
#biasanya diatas 70%
threshold=0.90
n_components=np.argmax(cumulative_variance>=threshold)+1
n_components

4

In [ ]:
#urutksn nilai dan vector eigen
sorted_indices= np.argsort(eigenvalues)[::-1] #mengurutkan dari besar kekecil
sorted_eigenvalues= eigenvalues[sorted_indices]
sorted_eigenvectors= eigenvectors[:, sorted_indices]

#mengambil komponen n_componen sebelumnya
n_components=1
W = sorted_eigenvectors[:, :n_components]
W

array([[-0.4978607 ],
       [-0.49607153],
       [-0.50354004],
       [-0.50248899]])

In [ ]:
#TRANSFORMASI DATA
Y= Z @ W
print("data setelah PCA:","\n", Y)

data setelah PCA: 
 [[-1.85364122]
 [ 2.95159575]
 [-1.54579331]
 [-0.29769242]
 [-3.46574526]
 [-1.33423136]
 [ 0.24222221]
 [ 2.066633  ]
 [ 0.90644968]
 [ 2.33020293]]


**PCA MENGGUNAKAN SKLEARN**

In [ ]:
#IMPORT LIBRARY
import numpy as np
from sklearn.decomposition import PCA

In [ ]:
#masukan data yang dignakan
data= np.array([
    [2.5, 2.4, 3.5, 3.6],
    [0.5, 0.7, 1.2, 1.3],
    [2.2, 2.9, 3.0, 3.4],
    [1.9, 2.2, 2.5, 2.7],
    [3.1, 3.6, 4.1, 4.0],
    [2.3, 2.7, 3.1, 3.0],
    [2.0, 1.6, 2.3, 2.4],
    [1.0, 1.1, 1.5, 1.6],
    [1.5, 1.6, 2.0, 2.1],
    [1.1, 0.9, 1.3, 1.4]
])

data


array([[2.5, 2.4, 3.5, 3.6],
       [0.5, 0.7, 1.2, 1.3],
       [2.2, 2.9, 3. , 3.4],
       [1.9, 2.2, 2.5, 2.7],
       [3.1, 3.6, 4.1, 4. ],
       [2.3, 2.7, 3.1, 3. ],
       [2. , 1.6, 2.3, 2.4],
       [1. , 1.1, 1.5, 1.6],
       [1.5, 1.6, 2. , 2.1],
       [1.1, 0.9, 1.3, 1.4]])

In [ ]:
#lakukann standaraisasi
import numpy as np
from sklearn.preprocessing import StandardScaler
scaler= StandardScaler()
scaled_data= scaler.fit_transform(data)
scaled_data

array([[ 0.92627881,  0.47833912,  1.13455516,  1.16201358],
       [-1.7585873 , -1.41276904, -1.35066091, -1.3833495 ],
       [ 0.52354889,  1.0345474 ,  0.5942908 ,  0.94067766],
       [ 0.12081898,  0.25585581,  0.05402644,  0.16600194],
       [ 1.73173864,  1.813239  ,  1.78287239,  1.60468542],
       [ 0.6577922 ,  0.81206409,  0.70234367,  0.49800582],
       [ 0.25506228, -0.41159413, -0.16207931, -0.16600194],
       [-1.08737078, -0.96780241, -1.02650229, -1.05134562],
       [-0.41615425, -0.41159413, -0.48623793, -0.49800582],
       [-0.95312747, -1.19028572, -1.24260803, -1.27268154]])

In [ ]:
#lakukan redukdi dengan PCA
#DIPILIH SATU KOMPONRN SESUAI N_COMPONEN
pca= PCA(n_components=1)
X_pca= pca.fit_transform(scaled_data)
#tampilkan hasil reduksi pca
print("data setelah direduksi mneggunakan PCA:","\n", X_pca)

data setelah direduksi mneggunakan PCA: 
 [[ 1.85364122]
 [-2.95159575]
 [ 1.54579331]
 [ 0.29769242]
 [ 3.46574526]
 [ 1.33423136]
 [-0.24222221]
 [-2.066633  ]
 [-0.90644968]
 [-2.33020293]]


**TUGAS MANDIRI **

In [ ]:
# HANYA MENGGUNAKAN LIBRARY NUMPY

import numpy as np


#Import data set
data1= np.array([
    [2.5, 0.5, 2.2, 1.9, 3.1, 2.3, 2.0, 1.0, 1.5, 1.1],
    [2.4, 0.7, 2.9, 2.2, 3.6, 2.7, 1.6, 1.1, 1.6, 0.9],
    [3.1, 1.0, 3.2, 2.5, 4.0, 3.1, 2.3, 1.5, 2.0, 1.3],
    [1.2, 0.5, 1.4, 1.0, 2.0, 1.7, 0.8, 0.7, 1.3, 0.9],
    [1.5, 0.3, 1.8, 1.2, 2.5, 1.9, 1.1, 0.9, 1.4, 0.7],
    [2.3, 0.8, 2.5, 1.8, 3.0, 2.6, 1.5, 1.0, 1.7, 1.0]
])
data1


array([[2.5, 0.5, 2.2, 1.9, 3.1, 2.3, 2. , 1. , 1.5, 1.1],
       [2.4, 0.7, 2.9, 2.2, 3.6, 2.7, 1.6, 1.1, 1.6, 0.9],
       [3.1, 1. , 3.2, 2.5, 4. , 3.1, 2.3, 1.5, 2. , 1.3],
       [1.2, 0.5, 1.4, 1. , 2. , 1.7, 0.8, 0.7, 1.3, 0.9],
       [1.5, 0.3, 1.8, 1.2, 2.5, 1.9, 1.1, 0.9, 1.4, 0.7],
       [2.3, 0.8, 2.5, 1.8, 3. , 2.6, 1.5, 1. , 1.7, 1. ]])

In [ ]:
#standarisasi
mean= np.mean(data1, axis=0)
std_dev= np.std(data1, axis=0)
Z= (data1-mean)/std_dev
Z



array([[ 0.52342392, -0.58345997, -0.21661214,  0.25400025,  0.10101525,
        -0.1745012 ,  0.88968025, -0.13736056, -0.36760731,  0.62609903],
       [ 0.36639675,  0.29172998,  0.92060161,  0.82550083,  0.85862966,
         0.66310457,  0.09885336,  0.27472113,  0.07352146, -0.4472136 ],
       [ 1.46558698,  1.60451491,  1.40797894,  1.3970014 ,  1.46472119,
         1.50071035,  1.48280041,  1.9230479 ,  1.83803656,  1.69941166],
       [-1.51792938, -0.58345997, -1.51628501, -1.46050146, -1.56573644,
        -1.43090987, -1.48280041, -1.37360564, -1.24986486, -0.4472136 ],
       [-1.04684785, -1.45864991, -0.86644858, -1.07950108, -0.80812204,
        -1.01210698, -0.88968025, -0.54944226, -0.80873608, -1.52052622],
       [ 0.20936957,  0.72932496,  0.27076518,  0.06350006, -0.05050763,
         0.45370313, -0.09885336, -0.13736056,  0.51465024,  0.08944272]])

In [ ]:
#HITUNG MATRIKS COVARIAN
cov_matrix = np.cov(Z, rowvar=False)
cov_matrix

#HITUNG NILAI EIGEN DAN VECTOR EIGEN
eigenvalues, eigenvectors = np.linalg.eigh(cov_matrix)

#hitung proporsi variansi dari niali eigen
total_variance = np.sum(eigenvalues)
proportions = eigenvalues / total_variance
#HITUNG KONTRIBUSI VARIANSI DARI NILAI EIGEN
cumulative_variance = np.cumsum(proportions)

#menampilkan hasil
print("Nilai Eigen:")
print(eigenvalues)
print("\nVector Eigen:")
print(eigenvectors)
print("\nProporsi Variansi:")
print(proportions)
print("\nKontribusi Variansi:")
print(cumulative_variance)


Nilai Eigen:
[-9.93534531e-16 -8.36627399e-17  1.24320662e-16  2.49345990e-16
  6.37611128e-16  5.16893598e-02  1.78304176e-01  5.27706960e-01
  6.17487769e-01  1.06248117e+01]

Vector Eigen:
[[ 0.38528754 -0.19647288  0.58699899  0.23388805  0.19730807 -0.40976319
  -0.16732817  0.26588079  0.00282126 -0.32885387]
 [-0.4086725  -0.00262509  0.27561533 -0.03009888  0.3150376   0.07939815
  -0.26068523 -0.62705595 -0.32117533 -0.29367984]
 [ 0.37592015  0.17434278 -0.51317532  0.06950004  0.53274278  0.0539032
  -0.15848171 -0.15930758  0.34429006 -0.32304495]
 [ 0.01574033  0.64660719  0.22927009 -0.12811526 -0.40452999  0.25304215
  -0.35215313  0.12233749  0.1960797  -0.3279828 ]
 [-0.32520846 -0.4435811  -0.08414648  0.5429619  -0.2082251   0.35490296
  -0.06742532  0.10530523  0.32409739 -0.32495958]
 [ 0.09484381 -0.45490955 -0.16923447 -0.59062495 -0.3822441  -0.25834135
  -0.14580815 -0.19647809  0.15803981 -0.32998907]
 [-0.56316724  0.1110342  -0.20344372 -0.22678846  0.276441

In [ ]:
#menentukan ambang batas atau threshold dala pemilhan eigen
#biasanya diatas 70%
threshold=0.80
n_components=np.argmax(cumulative_variance>=threshold)+1
print("ambang batas 80%:", n_components)
#urutksn nilai dan vector eigen
sorted_indices= np.argsort(eigenvalues)[::-1] #mengurutkan dari besar kekecil
sorted_eigenvalues= eigenvalues[sorted_indices]
sorted_eigenvectors= eigenvectors[:, sorted_indices]

print("\nNilai Eigen Setelah Diurutkan:")
print(sorted_eigenvalues)
print("\nVector Eigen Setelah Diurutkan:")
print(sorted_eigenvectors)

#mengambil komponen n_componen sebelumnya
n_components=1
W = sorted_eigenvectors[:, :n_components]
print(W)
#TRANSFORMASI DATA
Y= Z @ W
print("data setelah PCA:","\n", Y)


ambang batas 80%: 10

Nilai Eigen Setelah Diurutkan:
[ 1.06248117e+01  6.17487769e-01  5.27706960e-01  1.78304176e-01
  5.16893598e-02  6.37611128e-16  2.49345990e-16  1.24320662e-16
 -8.36627399e-17 -9.93534531e-16]

Vector Eigen Setelah Diurutkan:
[[-0.32885387  0.00282126  0.26588079 -0.16732817 -0.40976319  0.19730807
   0.23388805  0.58699899 -0.19647288  0.38528754]
 [-0.29367984 -0.32117533 -0.62705595 -0.26068523  0.07939815  0.3150376
  -0.03009888  0.27561533 -0.00262509 -0.4086725 ]
 [-0.32304495  0.34429006 -0.15930758 -0.15848171  0.0539032   0.53274278
   0.06950004 -0.51317532  0.17434278  0.37592015]
 [-0.3279828   0.1960797   0.12233749 -0.35215313  0.25304215 -0.40452999
  -0.12811526  0.22927009  0.64660719  0.01574033]
 [-0.32495958  0.32409739  0.10530523 -0.06742532  0.35490296 -0.2082251
   0.5429619  -0.08414648 -0.4435811  -0.32520846]
 [-0.32998907  0.15803981 -0.19647809 -0.14580815 -0.25834135 -0.3822441
  -0.59062495 -0.16923447 -0.45490955  0.09484381]
 [-

2. Buatlah program untuk mereduksi jumlah fitur dari data penyakit jantung di bawah ini
dengan ketentuan:
● Gunakan library sklearn
● Pilih komponen utama sebanyak 2.
● Data dapat dimasukkan manual melalui np.array atau langsung menggunakan
pd.read_csv() sebelum kemudian mengubahnya kedalam bentuk array
menggunakan fungsi pandas dataframe.to_numpy(). Data dapat diunduh pada
tautan https://shorturl.at/Dq1OO

In [ ]:
#menggunakan library sklearn
#IMPORT LIBRARY
import numpy as np
from sklearn.decomposition import PCA
import pandas as pd

#MEMBACA DATA
data= pd.read_csv("heart_fitur.csv")
data

#MENGUBAH BENTUK ARRAY
df= data.to_numpy()
df

array([[6.30e+01, 1.00e+00, 1.00e+00, 1.45e+02, 2.33e+02, 1.00e+00,
        2.00e+00, 1.50e+02, 0.00e+00, 2.30e+00, 3.00e+00, 0.00e+00,
        6.00e+00],
       [6.70e+01, 1.00e+00, 4.00e+00, 1.60e+02, 2.86e+02, 0.00e+00,
        2.00e+00, 1.08e+02, 1.00e+00, 1.50e+00, 2.00e+00, 3.00e+00,
        3.00e+00],
       [6.70e+01, 1.00e+00, 4.00e+00, 1.20e+02, 2.29e+02, 0.00e+00,
        2.00e+00, 1.29e+02, 1.00e+00, 2.60e+00, 2.00e+00, 2.00e+00,
        7.00e+00],
       [3.70e+01, 1.00e+00, 3.00e+00, 1.30e+02, 2.50e+02, 0.00e+00,
        0.00e+00, 1.87e+02, 0.00e+00, 3.50e+00, 3.00e+00, 0.00e+00,
        3.00e+00],
       [6.30e+01, 1.00e+00, 4.00e+00, 1.30e+02, 2.54e+02, 0.00e+00,
        2.00e+00, 1.47e+02, 0.00e+00, 1.40e+00, 2.00e+00, 1.00e+00,
        7.00e+00],
       [5.30e+01, 1.00e+00, 4.00e+00, 1.40e+02, 2.03e+02, 1.00e+00,
        2.00e+00, 1.55e+02, 1.00e+00, 3.10e+00, 3.00e+00, 0.00e+00,
        7.00e+00],
       [5.70e+01, 1.00e+00, 4.00e+00, 1.40e+02, 1.92e+02, 0.00e+00,
  

In [ ]:
#lakukann standaraisasi
import numpy as np
from sklearn.preprocessing import StandardScaler
scaler= StandardScaler()
scaled_data= scaler.fit_transform(df)
scaled_data

array([[ 1.01155159,  0.39223227, -2.22567029,  0.47702263, -0.21135989,
         1.6583124 ,  1.06904497, -0.16799656, -0.60302269,  0.8805602 ,
         1.60356745, -0.52764485,  0.57885968],
       [ 1.50903599,  0.39223227,  1.00514142,  1.57222763,  1.28891787,
        -0.60302269,  1.06904497, -2.37295135,  1.6583124 ,  0.10926659,
         0.26726124,  2.86435777, -1.04918318],
       [ 1.50903599,  0.39223227,  1.00514142, -1.34831905, -0.3245884 ,
        -0.60302269,  1.06904497, -1.27047396,  1.6583124 ,  1.1697953 ,
         0.26726124,  1.73369023,  1.12154064],
       [-2.22209695,  0.39223227, -0.07179582, -0.61818238,  0.26986128,
        -0.60302269, -0.93541435,  1.77446362, -0.60302269,  2.03750061,
         1.60356745, -0.52764485, -1.04918318],
       [ 1.01155159,  0.39223227,  1.00514142, -0.61818238,  0.38308979,
        -0.60302269,  1.06904497, -0.32549333, -0.60302269,  0.01285489,
         0.26726124,  0.60302269,  1.12154064],
       [-0.23215938,  0.392232

In [ ]:
#lakukan redukdi dengan PCA
#DIPILIH SATU KOMPONRN SESUAI N_COMPONEN
pca= PCA(n_components=1)
X_pca= pca.fit_transform(scaled_data)
#tampilkan hasil reduksi pca
print("data setelah direduksi mneggunakan PCA:","\n", X_pca)

data setelah direduksi mneggunakan PCA: 
 [[ 0.95415701]
 [ 3.87494073]
 [ 3.45834806]
 [-1.80634953]
 [ 1.36694326]
 [ 2.23261405]
 [-0.48668001]
 [-0.72343799]
 [ 1.91170781]
 [-2.40954875]
 [-1.00836399]
 [-1.6320316 ]
 [-1.33534801]
 [-2.00785739]
 [-2.38909366]]
